export const DARK_MODE_INDICATOR_CLASS = 'mode-dark';

export const DARK_MODE_STORAGE_KEY = DARK_MODE_INDICATOR_CLASS;

export const ACTION_TYPES = {
	TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE',
	SET_DARK_MODE: 'SET_DARK_MODE',
	MARK_THEME_AS_LOADED: 'MARK_THEME_AS_LOADED',
};
