version: "3"

services:
  ab-blog:
    container_name: ab-blog
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: ${DEVCONTAINER_VARIANT:-16-bullseye}
        BUILD_TZ: ${TZ:-Etc/UTC}
    environment:
      - PUID=1000
      - PGID=1000
    working_dir: /home/node/workspace
    volumes:
      - ..:/home/node/workspace:cached
      - ab-blog_node_modules:/home/node/workspace/node_modules
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: node

volumes:
  ab-blog_node_modules:
