# [Choice] Node.js version (use -bullseye variants on local arm64/Apple Silicon): 18, 16, 14, 18-bullseye, 16-bullseye, 14-bullseye, 18-buster, 16-buster, 14-buster
ARG VARIANT=16-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

# ARGs defined _after_ FROM can be used in ENV declarations
ARG BUILD_TZ=Etc/UTC

ENV npm_config_yes="true" EDITOR="/bin/nano" VISUAL="/bin/nano" TZ=${BUILD_TZ}

RUN chsh -s $(which zsh) root \
	&& chsh -s $(which zsh) node

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=10
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

RUN su node -c "npm install -g @antfu/ni@0.18.2 npm-check-updates@16.3.11"
