version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    default_reviewers:
      - 'andrewbrey'
    version_requirement_updates: 'auto'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'in_range'
      - match:
          dependency_type: 'production'
          update_type: 'in_range'
